### MY PROGRAMS

# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = yazi
$menu = rofi -show drun
$music = musicfox
$browser = zen
$editor = zeditor
$ide = rider

$active_border_color = rgba(c293a3ff)
$inactive_border_color = 0xff382D2E
