$wall = /usr/share/hypr/wall2.png

$fg_muted = rgba(808da0ff)
$brand = rgba(8cacccff)
$bg_border = rgba(484e5fff)
$role_info = rgba(3eb4c7ff)
$role_ok = rgba(41c272ff)
$role_warning = rgba(b6c053ff)
$role_error = rgba(c2715aff)
